'use client';

import { useRef, useEffect } from 'react';
import styles from './StoryExample.module.css';

const beats = [
  {
    tag: '0–4s · Opening',
    text: 'Medium shot on Joe, gently stroking the shimmering mane of a Unicorn in a lush, sun-dappled forest. Warm sunlight filters through watercolor-textured leaves; floating spirits drift peacefully around them.',
  },
  {
    tag: '4–9s · Development',
    text: 'Joe and the Unicorn walk along a winding forest path. The path opens onto a clearing with an ancient tree, its branches adorned with tiny luminous blossoms. The Unicorn nudges his side affectionately.',
  },
  {
    tag: '9–13s · Key moment',
    text: 'The tree shimmers and reveals a hidden archway leading to a magical countryside village, aglow with soft warm light. Whimsical creatures flutter by. Joe steps through, filled with peaceful adventure.',
  },
  {
    tag: '13–15s · Closing',
    text: 'Joe stands with the Unicorn on a gentle rise overlooking the cozy village. The Unicorn nuzzles his shoulder. The frame holds, the dreamy music fades, ending on a feeling of complete wonder.',
  },
];

export default function StoryExample() {
  const videoRef = useRef<HTMLVideoElement>(null);

  useEffect(() => {
    const video = videoRef.current;
    if (!video || !('IntersectionObserver' in window)) return;

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) video.play().catch(() => {});
        });
      },
      { threshold: 0.4 }
    );
    observer.observe(video);
    return () => observer.disconnect();
  }, []);

  function handleClick() {
    const video = videoRef.current;
    if (!video) return;
    video.paused ? video.play() : video.pause();
  }

  return (
    <section className={styles.section} id="example">
      <div className="container">
        <p className={styles.eyebrow}>A real example</p>
        <h2 className={styles.title}>From one prompt to a hand-painted adventure.</h2>
        <p className={styles.subtitle}>
          Here&apos;s a real 15-second video Tales generated for Joe. The prompt on the right is exactly what the AI saw.
        </p>

        <div className={styles.grid}>
          <div className={styles.videoWrap}>
            <div className={styles.videoFrame} onClick={handleClick}>
              <video
                ref={videoRef}
                src="/joe-unicorn.mp4"
                className={styles.video}
                playsInline
                muted
                loop
                preload="metadata"
              />
              <div className={styles.videoCaption}>
                <div className={styles.videoCapText}>&ldquo;Joe and the Unicorn walk through a sun-dappled forest…&rdquo;</div>
                <div className={styles.videoCapTag}>Dreamy Fantasy · Hand-painted</div>
              </div>
            </div>
            <p className={styles.videoMeta}>
              <strong>Your personalized story, ready in minutes.</strong>&nbsp; Powered by Gemini + Kling 3.0.
            </p>
          </div>

          <aside className={styles.promptCard}>
            <div className={styles.promptHead}>
              <div className={styles.promptHeadIcon}>
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M12 20h9" />
                  <path d="M16.5 3.5a2.121 2.121 0 1 1 3 3L7 19l-4 1 1-4z" />
                </svg>
              </div>
              <div>
                <div className={styles.promptHeadTitle}>The prompt</div>
                <div className={styles.promptHeadSub}>Generated by Gemini · 15-second shot script</div>
              </div>
            </div>

            <div className={styles.promptBody}>
              {beats.map((beat) => (
                <div key={beat.tag} className={styles.promptBeat}>
                  <span className={styles.promptBeatTag}>{beat.tag}</span>
                  <p>{beat.text}</p>
                </div>
              ))}
            </div>

            <div className={styles.promptFoot}>
              {['Hand-painted', 'Dreamy fantasy', 'Watercolor', 'Cinematic'].map((chip) => (
                <span key={chip} className={styles.promptChip}>{chip}</span>
              ))}
            </div>
          </aside>
        </div>
      </div>
    </section>
  );
}
